---
- name: "Create host group '{{ satellite_convert2rhel_hostgroup7 }}'"
  redhat.satellite.hostgroup:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organization: "{{ satellite_organization }}"
    name: "{{ satellite_convert2rhel_hostgroup7 }}"
    activation_keys: "{{ satellite_convert2rhel_key_centos7 }}"
  when: satellite_content_rhel_enable_rhel7

- name: "Create host group '{{ satellite_convert2rhel_hostgroup8 }}'"
  redhat.satellite.hostgroup:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organization: "{{ satellite_organization }}"
    name: "{{ satellite_convert2rhel_hostgroup8 }}"
    activation_keys: "{{ satellite_convert2rhel_key_centos8 }}"
  when: satellite_content_rhel_enable_rhel8

- name: "Create host group '{{ satellite_convert2rhel_hostgroup_oracle7 }}'"
  redhat.satellite.hostgroup:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organization: "{{ satellite_organization }}"
    name: "{{ satellite_convert2rhel_hostgroup_oracle7 }}"
    activation_keys: "{{ satellite_convert2rhel_key_oracle7 }}"
  when: satellite_convert2rhel_enable_oracle7

- name: "Create host group '{{ satellite_convert2rhel_hostgroup_oracle8 }}'"
  redhat.satellite.hostgroup:
    username: "{{ satellite_username }}"
    password: "{{ satellite_password }}"
    server_url: "{{ satellite_server_url }}"
    validate_certs: "{{ satellite_validate_certs | default(omit) }}"
    organization: "{{ satellite_organization }}"
    name: "{{ satellite_convert2rhel_hostgroup_oracle8 }}"
    activation_keys: "{{ satellite_convert2rhel_key_oracle8 }}"
  when: satellite_convert2rhel_enable_oracle8
